### ISSUE TITLE
Update project to work with the latest Flutter

### ISSUE THREAD

**Issue by artrmz** [artrmz/watermaniac#1]

**Comment by ludoo0d0a** [comment]
I applied my own custom [upgrade script](
https://gist.github.com/ludoo0d0a/12c013739c19c6e0998a19192674ee3d) on this project to use latest version of Flutter.
Works good :)

You can see results in my fork [upgrade branch](https://github.com/ludoo0d0a/watermaniac/tree/upgrade) + some screenshots

@artrmz Very good job !!!

**Comment by artrmz** [comment]
@ludoo0d0a Looking good! Feel free to make a pull request.

**Comment by ludoo0d0a** [comment]
Ok well , let's go then :)
